In [3]:
#important libaries to import-
import pandas as pd  #pandas [useful for loading the dataset]-numpy[to perform array]
import numpy as np

In [4]:
from google.colab import files        #uploading data into online notebook
uploaded = files.upload()

Saving sales_prediction.csv to sales_prediction.csv


In [5]:
#to load the data
dataset = pd.read_csv('sales_prediction.csv')       
print(dataset)

     AGE  SALARY  STATUS
0     54   98789       1
1     39   42131       0
2     38   25466       0
3     29   26543       0
4     19   65377       1
..   ...     ...     ...
194   35   46434       1
195   45   54775       1
196   57   98976       1
197   39   68999       0
198   39   45654       1

[199 rows x 3 columns]


In [6]:
#summarize dataset  
print(dataset.shape)           #no. of rows and columns
print(dataset.head(5))      #head(5)-top 5 values & tail(5)-bottom 5 values 

(199, 3)
   AGE  SALARY  STATUS
0   54   98789       1
1   39   42131       0
2   38   25466       0
3   29   26543       0
4   19   65377       1


In [9]:
#segregate dataset into x and y - inputs/outputs-independent/dependent variables
x = dataset.iloc[:, :-1].values
x

array([[   54, 98789],
       [   39, 42131],
       [   38, 25466],
       [   29, 26543],
       [   19, 65377],
       [   29, 24554],
       [   20, 36777],
       [   30, 86848],
       [   34, 48885],
       [   34, 54544],
       [   55, 76889],
       [   35, 36643],
       [   53, 64765],
       [   25, 36536],
       [   23, 65266],
       [   35, 26546],
       [   45, 25253],
       [   54, 56574],
       [   32, 75436],
       [   53, 34566],
       [   35, 64466],
       [   45, 64332],
       [   57, 43564],
       [   39, 36563],
       [   39, 34135],
       [   40, 56564],
       [   37, 54364],
       [   28, 54532],
       [   30, 12352],
       [   26, 12434],
       [   23, 78967],
       [   20, 23234],
       [   25, 54646],
       [   29, 67878],
       [   35, 45422],
       [   32, 54567],
       [   36, 67879],
       [   47, 65323],
       [   58, 45466],
       [   26, 56366],
       [   34, 32423],
       [   32, 63476],
       [   39, 54255],
       [   

In [10]:
#segregate dataset into x and y - inputs/outputs-independent/dependent variables
y = dataset.iloc[:, -1].values
y

array([1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0,
       1])

In [13]:
#spiliting the dataset into train and test-x_train&y_train is for train purpose where x_test&y_test is for test purpose.
from sklearn.model_selection  import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.25, random_state = 0)

In [14]:
#feacture scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)
print(x_train)

[[-1.10446026  0.17844971]
 [ 1.84609032  2.59762191]
 [ 0.41840455 -0.93275135]
 [ 0.03768835 -0.31821235]
 [-1.10446026  1.39505942]
 [ 0.1328674  -0.93275135]
 [-1.38999742  1.5081995 ]
 [ 1.37019506  1.50340819]
 [-0.34302785 -1.02596396]
 [ 0.60876266 -0.26311238]
 [ 1.46537411  0.069012  ]
 [-0.34302785  0.05817713]
 [-1.67553457  0.16271464]
 [ 1.46537411 -0.90928486]
 [-1.19963931 -0.80202502]
 [-0.53338596  0.96547559]
 [ 0.03768835  0.28745184]
 [ 0.1328674  -0.93275135]
 [ 0.22804645  1.50340819]
 [-1.19963931  0.16641701]
 [-0.2478488  -0.1910795 ]
 [ 1.08465791  0.17779635]
 [ 1.17983696 -2.11876206]
 [-0.81892311 -0.1910795 ]
 [ 0.22804645  0.76826994]
 [-0.72374406 -1.03511099]
 [ 1.56055316 -0.30514517]
 [-1.38999742  0.76222636]
 [-0.91410216  0.17779635]
 [ 0.60876266  0.27765145]
 [ 1.56055316 -0.26311238]
 [ 1.75091127 -0.30514517]
 [-0.2478488  -0.26311238]
 [-1.67553457  0.10821357]
 [-1.77071362  2.58744039]
 [ 0.03768835 -1.40474909]
 [ 0.60876266  0.96547559]
 

In [15]:
#training 
from sklearn.linear_model import LogisticRegression
model = LogisticRegression() #loading the alg
model.fit(x_train,y_train)      #train

LogisticRegression()

In [16]:
#prediction for all the test data 
y_pred = model.predict(x_test)

In [17]:
#to get the accuracy of the model
from sklearn.metrics import accuracy_score
print("accuracy of the model:{0}%".format(accuracy_score(y_test,y_pred)*100))

accuracy of the model:48.0%


In [20]:
#deploying on teh project
#predicting , weather new customer with age and salary will buy or not

age = int(input("enter customer age : "))
salary = int(input("enter customer salary : "))
newCust = [[age,salary]]
result = model.predict(sc.transform(newCust))
print(result)
if result == 1:
  print("customer will buy ")
else:
  print("customer won't buy")

enter customer age : 27
enter customer salary : 0
[1]
customer will buy 
